const fs = require("fs");
const path = require("path");

const ROOMS_DIR = path.join(__dirname, "../public/assets/rooms");
const TARGET_FILE = path.join(__dirname, "../src/data/rooms.ts");

function scanAndGenerate() {
  console.log("Scanning public/assets/rooms/ for room images...");

  if (!fs.existsSync(ROOMS_DIR)) {
    console.error(`Rooms directory does not exist at: ${ROOMS_DIR}`);
    return;
  }

  const files = fs.readdirSync(ROOMS_DIR);
  const imageExtensions = [".jpg", ".jpeg", ".png", ".webp"];
  const images = files.filter((file) => {
    const ext = path.extname(file).toLowerCase();
    return imageExtensions.includes(ext);
  });

  const singleDeluxeImages = [];
  const familyRoomImages = [];

  images.forEach((file) => {
    const filePath = `/assets/rooms/${file}`;
    const lowerName = file.toLowerCase();

    // Grouping: Deluxe images contain 11.30.09 and others go to Single Deluxe. Let's make a clean split.
    if (
      lowerName.includes("11.30.09") ||
      lowerName.includes("11.30.08") ||
      lowerName.includes("deluxe")
    ) {
      singleDeluxeImages.push(filePath);
    } else {
      familyRoomImages.push(filePath);
    }
  });

  singleDeluxeImages.sort();
  familyRoomImages.sort();

  console.log(`Found:
- Single Deluxe Room: ${singleDeluxeImages.length} images
- Family Room: ${familyRoomImages.length} images`);

  const tsContent = `/**
 * HOTEL YASH GRAND - DYNAMIC ROOMS DATABASE
 * Auto-generated by scripts/scan-rooms.js. Do not edit manually.
 */

export interface Room {
  id: string;
  name: string;
  slug: string;
  description: string;
  images: string[];
  price: number;
  capacity: number;
  bedType: string;
  size: string;
  amenities: string[];
  featured: boolean;
  available: boolean;
  badge?: string;
}

export const ROOMS_DATA: Room[] = [
  {
    id: "single-deluxe",
    name: "Single Deluxe Room",
    slug: "single-deluxe",
    description: "A modern and comfortable room ideal for couples and business travellers. Located near Heritage Hospital, SHEPA College and within walking distance of SMS College, it offers a peaceful stay with premium amenities and convenient access to important city destinations.",
    images: ${JSON.stringify(singleDeluxeImages, null, 4)},
    price: 2500,
    capacity: 2,
    bedType: "Gourmet Double Bed",
    size: "280 sq ft",
    amenities: [
      "Highway View",
      "Attached Balcony",
      "24×7 High-Speed Wi-Fi",
      "24×7 Room Service",
      "Direct Food Ordering from HOTEL YASH GRAND Restaurant",
      "LED Smart TV",
      "Air Conditioner",
      "Premium Washroom",
      "Daily Housekeeping",
      "Fresh Linen"
    ],
    featured: true,
    available: true,
    badge: "⭐ Best Value"
  },
  {
    id: "family-room",
    name: "Family Room",
    slug: "family-room",
    description: "A spacious family accommodation consisting of two connected rooms. Perfect for families visiting Varanasi, with easy access to Heritage Hospital, SHEPA College and SMS College, while enjoying comfort, privacy and premium hospitality.",
    images: ${JSON.stringify(familyRoomImages, null, 4)},
    price: 4000,
    capacity: 4,
    bedType: "Two Connected Rooms",
    size: "480 sq ft",
    amenities: [
      "Two Connected Rooms",
      "Highway View",
      "Attached Balcony",
      "24×7 High-Speed Wi-Fi",
      "24×7 Room Service",
      "Direct Food Ordering from HOTEL YASH GRAND Restaurant",
      "LED Smart TV",
      "Air Conditioner",
      "Premium Washroom",
      "Daily Housekeeping",
      "Fresh Linen"
    ],
    featured: true,
    available: true,
    badge: "👨\u200D👩\u200D👧 Perfect for Families"
  }
];
`;

  fs.writeFileSync(TARGET_FILE, tsContent, "utf8");
  console.log(`Successfully generated ${TARGET_FILE}`);
}

scanAndGenerate();
