/**
 * HOTEL YASH GRAND - DYNAMIC ROOMS DATABASE
 * Auto-generated by scripts/scan-rooms.js. Do not edit manually.
 */

export interface Room {
  id: string;
  name: string;
  slug: string;
  description: string;
  images: string[];
  price: number;
  capacity: number;
  bedType: string;
  size: string;
  amenities: string[];
  featured: boolean;
  available: boolean;
  badge?: string;
}

export const ROOMS_DATA: Room[] = [
  {
    id: "single-deluxe",
    name: "Single Deluxe Room",
    slug: "single-deluxe",
    description: "A modern and comfortable room ideal for couples and business travellers. Located near Heritage Hospital, SHEPA College and within walking distance of SMS College, it offers a peaceful stay with premium amenities and convenient access to important city destinations.",
    images: [
    "/assets/rooms/WhatsApp Image 2026-07-11 at 11.30.08-2.jpeg",
    "/assets/rooms/WhatsApp Image 2026-07-11 at 11.30.09-2.jpeg",
    "/assets/rooms/WhatsApp Image 2026-07-11 at 11.30.09.jpeg"
],
    price: 2500,
    capacity: 2,
    bedType: "Gourmet Double Bed",
    size: "280 sq ft",
    amenities: [
      "Highway View",
      "Attached Balcony",
      "24×7 High-Speed Wi-Fi",
      "24×7 Room Service",
      "Direct Food Ordering from HOTEL YASH GRAND Restaurant",
      "LED Smart TV",
      "Air Conditioner",
      "Premium Washroom",
      "Daily Housekeeping",
      "Fresh Linen"
    ],
    featured: true,
    available: true,
    badge: "⭐ Best Value"
  },
  {
    id: "family-room",
    name: "Family Room",
    slug: "family-room",
    description: "A spacious family accommodation consisting of two connected rooms. Perfect for families visiting Varanasi, with easy access to Heritage Hospital, SHEPA College and SMS College, while enjoying comfort, privacy and premium hospitality.",
    images: [
    "/assets/rooms/WhatsApp Image 2026-07-11 at 11.30.03-2.jpeg",
    "/assets/rooms/WhatsApp Image 2026-07-11 at 11.30.03.jpeg",
    "/assets/rooms/WhatsApp Image 2026-07-11 at 11.30.04-2.jpeg",
    "/assets/rooms/WhatsApp Image 2026-07-11 at 11.30.04.jpeg",
    "/assets/rooms/WhatsApp Image 2026-07-11 at 11.30.10.jpeg"
],
    price: 4000,
    capacity: 4,
    bedType: "Two Connected Rooms",
    size: "480 sq ft",
    amenities: [
      "Two Connected Rooms",
      "Highway View",
      "Attached Balcony",
      "24×7 High-Speed Wi-Fi",
      "24×7 Room Service",
      "Direct Food Ordering from HOTEL YASH GRAND Restaurant",
      "LED Smart TV",
      "Air Conditioner",
      "Premium Washroom",
      "Daily Housekeeping",
      "Fresh Linen"
    ],
    featured: true,
    available: true,
    badge: "👨‍👩‍👧 Perfect for Families"
  }
];
